# Generated by Django 4.1.7 on 2023-03-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_estudiantes_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='clase',
        ),
    ]
