# Generated by Django 4.1.7 on 2023-03-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_remove_profesores_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='documento',
            field=models.IntegerField(),
        ),
    ]
